In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
data=pd.read_csv("/content/Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [ ]:
data.shape

(545, 13)

In [ ]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
x=data[['area','bedrooms','bathrooms']]
y=data['price']

In [ ]:
x

     area  bedrooms  bathrooms
0    7420         4          2
1    8960         4          4
2    9960         3          2
3    7500         4          2
4    7420         4          1
..    ...       ...        ...
540  3000         2          1
541  2400         3          1
542  3620         2          1
543  2910         3          1
544  3850         3          1

[545 rows x 3 columns]

In [ ]:
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [ ]:
x

     area  bedrooms  bathrooms
0    7420         4          2
1    8960         4          4
2    9960         3          2
3    7500         4          2
4    7420         4          1
..    ...       ...        ...
540  3000         2          1
541  2400         3          1
542  3620         2          1
543  2910         3          1
544  3850         3          1

[545 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=23)

In [ ]:
from sklearn.linear_model import LinearRegression
ols=LinearRegression()
ols.fit(x_train,y_train)
prediction=ols.predict(x_test)

In [ ]:
from sklearn.metrics import mean_squared_error as mse
print('OLS',mse(y_test,prediction))
print('OLS',np.sqrt(mse(y_test,prediction)))

OLS 1584547193065.3542
OLS 1258787.9857487336

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
from sklearn.linear_model import SGDRegressor
lr=SGDRegressor()
lr.fit(x_train,y_train)
prediction2=lr.predict(x_test)

In [ ]:
print('Linear Regression test',mse(y_test,prediction2))
print('Linear Regression train',mse(y_train,lr.predict(x_train)))
print('Linear Regression test',np.sqrt(mse(y_test,prediction2)))

Linear Regression test 2108541820319.4126
Linear Regression train 2308995680781.1714
Linear Regression test 1452081.8917400674